/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/voice-partition-theme.js
 * Command: astryx theme build src/theme/voice-partition-theme.js
 * CLI: @astryxdesign/cli@0.4.7
 * Core: @astryxdesign/core@0.4.7
 */

/// <reference path="./voice-partition.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const voicePartitionTheme: DefinedTheme;
