/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/voice-partition-theme.js
 * Command: astryx theme build src/theme/voice-partition-theme.js
 * CLI: @astryxdesign/cli@0.4.7
 * Core: @astryxdesign/core@0.4.7
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
